//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid SmartBat = new Guid("36ea3256-4daf-4c74-af38-ca87192608cd");
		public static readonly Guid Test = new Guid("84848038-b286-432c-9ef2-8f5a2ddca23d");

    }
}
