//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid SmartBatAi = new Guid("fcfd9e6c-6717-47ab-80c6-b5bb882604f4");

    }
}
